### ISSUE TITLE
No add-on anymore 

### ISSUE THREAD

**Issue by vindarel** [vale981/practical-cl-beautified#1]
Hello,
We can not find your add-on on the Mozilla Extensions page anymore :( 
https://addons.mozilla.org/de/firefox/addon/beautify-practical-common-lisp/?src=search
Do you know what's happening ? Will it be back ? Would you put installation instructions otherwise ?

(we link it in the "Awesome CL" list https://github.com/CodyReichert/awesome-cl/pull/266)

thank you

**Comment by vale981** [comment]
Sorry. Got a bit busy. I'll look at it!

**Comment by vale981** [comment]
I've added a binary release until it's listed again.

https://github.com/vale981/practical-cl-beautified/releases/latest
