### ISSUE TITLE
Index page is empty

### ISSUE THREAD

**Issue by pvonmoradi** [vale981/practical-cl-beautified#2]
After pressing `h` button, index page is not rendered. I believe "https://gigamonkeys.com/book/index.html" should be replaced with "https://gigamonkeys.com/book/" somewhere.

**Comment by vale981** [comment]
hmm it still works for me... i'll look into it

**Comment by vale981** [comment]
https://github.com/vale981/practical-cl-beautified/releases/tag/v1.5.3
should fix it
