### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by danielnemenyi** [vale981/practical-cl-beautified#3]
Hello, thanks for putting this together but the plugin (1.5.3) doesn't seem to be working for me on Firefox (123.0). I've tried refreshing [gigamonkeys site](https://gigamonkeys.com/book/) with the cache disabled in Developer Tools, opening it in a private window with Run in Private Windows allowed, and restarting Firefox but there's still not change to the syntax highlighting and the quick nav buttons aren't triggering anything. 

![image](https://github.com/vale981/practical-cl-beautified/assets/8701448/fa98dd5b-acdf-4806-88a2-5dfa77e08efd)

**Comment by vale981** [comment]
i haven't used the plugin in quite some while, but i'll have a look if I find the time

**Comment by vale981** [comment]
see release

**Comment by vale981** [comment]
(added signed xpi)

**Comment by danielnemenyi** [comment]
Excellent, works well. Thank you!
